### ISSUE TITLE
Práctica de hilos

### ISSUE THREAD

**Issue by Ferch0419** [SistemasTecTlaxiaco/practica-de-hilos-Ferch0419#2]
[Práctica Análisis de Hilos.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-hilos-Ferch0419/files/6516720/Practica.Analisis.de.Hilos.pdf)

**Comment by MariaC232** [comment]
Calificación: 20%
Buen trabajo.

**Comment by josealfredo79** [comment]
Bien hecho y revisado
